import { type VennData } from "./venn";

export const teamStrengthData: VennData = {
  label: "NOS FORCES",
  title: "Une synergie unique de talents au service de",
  titleAccent: "votre vision.",
  ellipses: [
    {
      id: "rigueur",
      label: "Rigueur Technique",
      shortLabel: "Code",
      desc: "Une culture de l'excellence où chaque ligne de code est optimisée pour la performance et la maintenabilité.",
      ix: 222,
      iy: 220,
      irx: 70,
      iry: 64,
      fx: 250,
      fy: 165,
      frx: 105,
      fry: 105,
      color: "var(--color-subtle)",
      lx: 250,
      ly: 115,
    },
    {
      id: "creativite",
      label: "Créativité Audacieuse",
      shortLabel: "Design",
      desc: "L'audace de repousser les limites du design pour créer des produits qui marquent les esprits.",
      ix: 250,
      iy: 220,
      irx: 70,
      iry: 64,
      fx: 180,
      fy: 285,
      frx: 105,
      fry: 105,
      color: "var(--color-subtle)",
      lx: 125,
      ly: 330,
    },
    {
      id: "strategie",
      label: "Vision Stratégique",
      shortLabel: "Impact",
      desc: "Une compréhension profonde des enjeux business pour aligner la technologie sur vos objectifs de croissance.",
      ix: 278,
      iy: 220,
      irx: 70,
      iry: 64,
      fx: 320,
      fy: 285,
      frx: 105,
      fry: 105,
      color: "var(--color-subtle)",
      lx: 375,
      ly: 330,
    },
  ],
  intersectionTitle: "L'ADN Otopio",
  intersectionDesc:
    "C'est ici que l'impact se crée : quand la maîtrise technique rencontre l'innovation visuelle et la stratégie métier pour donner naissance à des produits d'exception.",
};
