/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetsIndexRouteImport } from './routes/projets/index'
import { Route as ExpertisesIndexRouteImport } from './routes/expertises/index'
import { Route as ProjetsProjectIdRouteImport } from './routes/projets/$projectId'
import { Route as ExpertisesServiceIdRouteImport } from './routes/expertises/$serviceId'

const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsIndexRoute = ProjetsIndexRouteImport.update({
  id: '/projets/',
  path: '/projets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertisesIndexRoute = ExpertisesIndexRouteImport.update({
  id: '/expertises/',
  path: '/expertises/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsProjectIdRoute = ProjetsProjectIdRouteImport.update({
  id: '/projets/$projectId',
  path: '/projets/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertisesServiceIdRoute = ExpertisesServiceIdRouteImport.update({
  id: '/expertises/$serviceId',
  path: '/expertises/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/maintenance': typeof MaintenanceRoute
  '/expertises/$serviceId': typeof ExpertisesServiceIdRoute
  '/projets/$projectId': typeof ProjetsProjectIdRoute
  '/expertises/': typeof ExpertisesIndexRoute
  '/projets/': typeof ProjetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/maintenance': typeof MaintenanceRoute
  '/expertises/$serviceId': typeof ExpertisesServiceIdRoute
  '/projets/$projectId': typeof ProjetsProjectIdRoute
  '/expertises': typeof ExpertisesIndexRoute
  '/projets': typeof ProjetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/equipe': typeof EquipeRoute
  '/maintenance': typeof MaintenanceRoute
  '/expertises/$serviceId': typeof ExpertisesServiceIdRoute
  '/projets/$projectId': typeof ProjetsProjectIdRoute
  '/expertises/': typeof ExpertisesIndexRoute
  '/projets/': typeof ProjetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/blog'
    | '/contact'
    | '/equipe'
    | '/maintenance'
    | '/expertises/$serviceId'
    | '/projets/$projectId'
    | '/expertises/'
    | '/projets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/blog'
    | '/contact'
    | '/equipe'
    | '/maintenance'
    | '/expertises/$serviceId'
    | '/projets/$projectId'
    | '/expertises'
    | '/projets'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/blog'
    | '/contact'
    | '/equipe'
    | '/maintenance'
    | '/expertises/$serviceId'
    | '/projets/$projectId'
    | '/expertises/'
    | '/projets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  EquipeRoute: typeof EquipeRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ExpertisesServiceIdRoute: typeof ExpertisesServiceIdRoute
  ProjetsProjectIdRoute: typeof ProjetsProjectIdRoute
  ExpertisesIndexRoute: typeof ExpertisesIndexRoute
  ProjetsIndexRoute: typeof ProjetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/': {
      id: '/projets/'
      path: '/projets'
      fullPath: '/projets/'
      preLoaderRoute: typeof ProjetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertises/': {
      id: '/expertises/'
      path: '/expertises'
      fullPath: '/expertises/'
      preLoaderRoute: typeof ExpertisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/$projectId': {
      id: '/projets/$projectId'
      path: '/projets/$projectId'
      fullPath: '/projets/$projectId'
      preLoaderRoute: typeof ProjetsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expertises/$serviceId': {
      id: '/expertises/$serviceId'
      path: '/expertises/$serviceId'
      fullPath: '/expertises/$serviceId'
      preLoaderRoute: typeof ExpertisesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  EquipeRoute: EquipeRoute,
  MaintenanceRoute: MaintenanceRoute,
  ExpertisesServiceIdRoute: ExpertisesServiceIdRoute,
  ProjetsProjectIdRoute: ProjetsProjectIdRoute,
  ExpertisesIndexRoute: ExpertisesIndexRoute,
  ProjetsIndexRoute: ProjetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
